// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpnlfvaqlndmrtsngwme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwbmxmdmFxbG5kbXJ0c25nd21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mjc1MzIsImV4cCI6MjA2MDAwMzUzMn0.a-dqDg9rSXC-MNJNVcAXBT6mEIkupkJVrMbC5h6t-vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);